### PR TITLE
Added gif in `readme.md` file .

### PR DESCRIPTION
**Pull request by Kushal997-das**
working

### CODE REVIEW

**Comment by SamarpanCoder2002** [comment]
@Kushal997-das the GIF file is really cool but the position of that GIF is not satisfied in the readme. Please add this GIF to the upper section of the app images. just maintain a thing, after the gif file, all app images should be shown there. The gif file should not be beside the app images. 

Hope you understand. Thank u @Kushal997-das

**Review by SamarpanCoder2002 — CHANGES_REQUESTED** [review]
@Kushal997-das  the GIF file is really cool but the position of that GIF is not satisfied in the readme. Please add this GIF to the upper section of the app images. just maintain a thing, after the gif file, all app images should be shown there. The gif file should not be beside the app images.

Hope you understand. Thank u @Kushal997-das

**Comment by Kushal997-das** [comment]
@SamarpanCoder2002 Now check.

**Review by SamarpanCoder2002 — APPROVED** [review]
@Kushal997-das It looks awesome. LGTM.

**Pull request merged**
